# File: backend/src/main/resources/application.yml

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_sri_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Colombo

file:
  upload-dir: uploads

logging:
  level:
    com.travelsri: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
management:
  endpoints:
    web:
      exposure:
        include: health,info


# JWT Configuration
jwt:
  secret: ${JWT_SECRET:TravelSriSecretKey2024ForHotelAndUserAuthentication}
  expiration-ms: 86400000

# PayHere Configuration
payhere:
  merchant:
    id: ${PAYHERE_MERCHANT_ID:1231576}
    secret: ${PAYHERE_MERCHANT_SECRET:MTg0NTAxODI1MjQ1NzY3MDI0MTQ1NTUzMTA2MzExMzI0NjIwODk=}
  api:
    base-url: ${PAYHERE_BASE_URL:https://sandbox.payhere.lk/pay/checkout}
    # For live: https://www.payhere.lk/pay/checkout


# Application Configuration
app:
  base:
    url: ${APP_BASE_URL:http://localhost:8080}

